// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function AddAttachment():Promise<string>;

export function CancelSending():Promise<void>;

export function ConvertImageToBase64(arg1:string):Promise<string>;

export function DeleteAccount(arg1:string):Promise<string>;

export function DeleteAllLogFiles():Promise<void>;

export function DeleteLogFile(arg1:string):Promise<void>;

export function DeleteTemplate(arg1:string):Promise<string>;

export function ExportUserData(arg1:string):Promise<void>;

export function FilterContacts(arg1:string):Promise<void>;

export function GetAccounts():Promise<Array<main.Account>>;

export function GetAllContacts():Promise<Array<main.Contact>>;

export function GetAppDataLocation():Promise<string>;

export function GetAppDataSize():Promise<Record<string, any>>;

export function GetAttachments():Promise<Array<main.AttachmentInfo>>;

export function GetDefaultExportPath():Promise<string>;

export function GetFields():Promise<Array<string>>;

export function GetFilteredContacts():Promise<Array<main.Contact>>;

export function GetInvalidContacts():Promise<Array<main.Contact>>;

export function GetLogFiles():Promise<Array<string>>;

export function GetSelectedRows():Promise<Array<number>>;

export function GetSettings():Promise<main.Settings>;

export function GetTemplate(arg1:string):Promise<main.Template>;

export function GetTemplates():Promise<Array<main.Template>>;

export function ImportAccountsFromDir(arg1:string):Promise<number>;

export function ImportSettingsFromDir(arg1:string):Promise<void>;

export function ImportTemplatesFromDir(arg1:string):Promise<number>;

export function ImportUserData(arg1:string):Promise<void>;

export function LoadAccounts():Promise<Array<main.Account>>;

export function LoadContacts(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function LoadFieldsFromFile(arg1:string,arg2:string):Promise<Array<string>>;

export function LoadTablesOrFields(arg1:string,arg2:string):Promise<Array<string>>;

export function LoadTemplates():Promise<Array<main.Template>>;

export function Log(arg1:string,arg2:string):Promise<void>;

export function LogMessage(arg1:string):Promise<void>;

export function PauseSending():Promise<void>;

export function ReadLogFile(arg1:string):Promise<string>;

export function ResumeSending():Promise<void>;

export function SaveAccount(arg1:main.Account):Promise<string>;

export function SaveAccounts():Promise<void>;

export function SaveAttachmentFile(arg1:string,arg2:string):Promise<string>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function SaveTemplate(arg1:main.Template):Promise<string>;

export function SaveTemplates():Promise<void>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectFile(arg1:string):Promise<string>;

export function SelectSourceFile(arg1:string):Promise<string>;

export function SendEmails(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<void>;

export function SendEmailsWithTheme(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>,arg6:boolean):Promise<void>;

export function SetMapping(arg1:Record<string, string>):Promise<void>;

export function SetSelectedRows(arg1:Array<number>):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function SyncAttachments(arg1:Array<string>):Promise<string>;

export function TestSMTPConnection(arg1:main.Account):Promise<string>;

export function UninstallApp(arg1:boolean,arg2:string):Promise<Record<string, any>>;

export function UpdateSettings(arg1:main.Settings):Promise<void>;
