// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAttachment() {
  return window['go']['main']['App']['AddAttachment']();
}

export function CancelSending() {
  return window['go']['main']['App']['CancelSending']();
}

export function ConvertImageToBase64(arg1) {
  return window['go']['main']['App']['ConvertImageToBase64'](arg1);
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function DeleteAllLogFiles() {
  return window['go']['main']['App']['DeleteAllLogFiles']();
}

export function DeleteLogFile(arg1) {
  return window['go']['main']['App']['DeleteLogFile'](arg1);
}

export function DeleteTemplate(arg1) {
  return window['go']['main']['App']['DeleteTemplate'](arg1);
}

export function ExportUserData(arg1) {
  return window['go']['main']['App']['ExportUserData'](arg1);
}

export function FilterContacts(arg1) {
  return window['go']['main']['App']['FilterContacts'](arg1);
}

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetAllContacts() {
  return window['go']['main']['App']['GetAllContacts']();
}

export function GetAppDataLocation() {
  return window['go']['main']['App']['GetAppDataLocation']();
}

export function GetAppDataSize() {
  return window['go']['main']['App']['GetAppDataSize']();
}

export function GetAttachments() {
  return window['go']['main']['App']['GetAttachments']();
}

export function GetDefaultExportPath() {
  return window['go']['main']['App']['GetDefaultExportPath']();
}

export function GetFields() {
  return window['go']['main']['App']['GetFields']();
}

export function GetFilteredContacts() {
  return window['go']['main']['App']['GetFilteredContacts']();
}

export function GetInvalidContacts() {
  return window['go']['main']['App']['GetInvalidContacts']();
}

export function GetLogFiles() {
  return window['go']['main']['App']['GetLogFiles']();
}

export function GetSelectedRows() {
  return window['go']['main']['App']['GetSelectedRows']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTemplate(arg1) {
  return window['go']['main']['App']['GetTemplate'](arg1);
}

export function GetTemplates() {
  return window['go']['main']['App']['GetTemplates']();
}

export function ImportAccountsFromDir(arg1) {
  return window['go']['main']['App']['ImportAccountsFromDir'](arg1);
}

export function ImportSettingsFromDir(arg1) {
  return window['go']['main']['App']['ImportSettingsFromDir'](arg1);
}

export function ImportTemplatesFromDir(arg1) {
  return window['go']['main']['App']['ImportTemplatesFromDir'](arg1);
}

export function ImportUserData(arg1) {
  return window['go']['main']['App']['ImportUserData'](arg1);
}

export function LoadAccounts() {
  return window['go']['main']['App']['LoadAccounts']();
}

export function LoadContacts(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LoadContacts'](arg1, arg2, arg3, arg4);
}

export function LoadFieldsFromFile(arg1, arg2) {
  return window['go']['main']['App']['LoadFieldsFromFile'](arg1, arg2);
}

export function LoadTablesOrFields(arg1, arg2) {
  return window['go']['main']['App']['LoadTablesOrFields'](arg1, arg2);
}

export function LoadTemplates() {
  return window['go']['main']['App']['LoadTemplates']();
}

export function Log(arg1, arg2) {
  return window['go']['main']['App']['Log'](arg1, arg2);
}

export function LogMessage(arg1) {
  return window['go']['main']['App']['LogMessage'](arg1);
}

export function PauseSending() {
  return window['go']['main']['App']['PauseSending']();
}

export function ReadLogFile(arg1) {
  return window['go']['main']['App']['ReadLogFile'](arg1);
}

export function ResumeSending() {
  return window['go']['main']['App']['ResumeSending']();
}

export function SaveAccount(arg1) {
  return window['go']['main']['App']['SaveAccount'](arg1);
}

export function SaveAccounts() {
  return window['go']['main']['App']['SaveAccounts']();
}

export function SaveAttachmentFile(arg1, arg2) {
  return window['go']['main']['App']['SaveAttachmentFile'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveTemplate(arg1) {
  return window['go']['main']['App']['SaveTemplate'](arg1);
}

export function SaveTemplates() {
  return window['go']['main']['App']['SaveTemplates']();
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}

export function SelectSourceFile(arg1) {
  return window['go']['main']['App']['SelectSourceFile'](arg1);
}

export function SendEmails(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SendEmails'](arg1, arg2, arg3, arg4, arg5);
}

export function SendEmailsWithTheme(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SendEmailsWithTheme'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SetMapping(arg1) {
  return window['go']['main']['App']['SetMapping'](arg1);
}

export function SetSelectedRows(arg1) {
  return window['go']['main']['App']['SetSelectedRows'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['main']['App']['Shutdown'](arg1);
}

export function SyncAttachments(arg1) {
  return window['go']['main']['App']['SyncAttachments'](arg1);
}

export function TestSMTPConnection(arg1) {
  return window['go']['main']['App']['TestSMTPConnection'](arg1);
}

export function UninstallApp(arg1, arg2) {
  return window['go']['main']['App']['UninstallApp'](arg1, arg2);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
